name: "Dependabot Auto Merge"

on:
    pull_request:

jobs:
    auto-merge:
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v2

            -   name: "Auto Merge"
                uses: ahmadnassri/action-dependabot-auto-merge@v2
                with:
                    target: minor
                    github-token: ${{ secrets.PRIVATE_TOKEN }}
